Feature: Look-and-Say Sequence Length

  Rule: Look-and-say sequence generation
    The look-and-say sequence is generated by reading the previous sequence and encoding it.
    - Each run of consecutive digits is replaced by the count of digits followed by the digit itself.
    - This process is repeated iteratively for a given number of steps.

  Scenario: Generate the length of the result after 40 iterations
    Given the initial sequence is "1321131112"
    When the look-and-say process is applied 40 times
    Then the length of the resulting sequence is calculated

  Examples:
    | Input       | Iterations | Intermediate Step              | Result Length |
    | 1           | 1          | 11 (1 one)                     | 2             |
    | 11          | 1          | 21 (2 ones)                    | 2             |
    | 21          | 1          | 1211 (1 two, 1 one)            | 4             |
    | 1211        | 1          | 111221 (1 one, 1 two, 2 ones)  | 6             |
    | 111221      | 1          | 312211 (3 ones, 2 twos, 1 one) | 6             |
    | 1321131112  | 40         | N/A                            | (final length after 40 steps) |